# Default settings for build.sh.

# Lustre source tarball to build, located in src/.
# Can be overridden with "build.sh --source NAME" or the LUSTRE_SOURCE variable.
LUSTRE_SOURCE=lustre-2.14.0_ddn249.tar.gz
